Repository sealsystems/node-log, pull requests merged in 2021-08, with the labels that each got.

#276 Update build configuration
  .github/workflows/publish-on-npmjs-org.yml
  .github/workflows/release.yml
  .github/workflows/test.yml
  .github/workflows/update-build-config.yml
  package-lock.json
Labels: automatic-merge

#277 feat: transform metadata to object
  README.md
  lib/logger.js
  package-lock.json
  package.json
  test/loggerTest.js
Labels: release/minor, release/feat

#278 chore: Use default formatter instead of fix creating json
  lib/logger.js
Labels: release/patch, release/chore
